eureka:
 client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:12345/eureka
    
 server:
    waitTimeInMsWhenSyncEmpty: 0
server:
  port: 12345
  
